// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversityRegistration.Data;

#nullable disable

namespace AcademicEnrollment.Migrations
{
    [DbContext(typeof(UniversityRegistrationContext))]
    [Migration("20251001031216_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniversityRegistration.Models.ChuongTrinhHoc", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("id");

                    b.Property<string>("TenChuongTrinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_chuong_trinh");

                    b.HasKey("Id")
                        .HasName("pk_chuong_trinh_hoc");

                    b.ToTable("chuong_trinh_hoc");
                });

            modelBuilder.Entity("UniversityRegistration.Models.DangKyHocPhan", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("id");

                    b.Property<string>("LopHocPhanId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("lop_hoc_phan_id");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_dang_ky");

                    b.Property<string>("NhomThucHanhId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("nhom_thuc_hanh_id");

                    b.Property<string>("SinhVienId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("sinh_vien_id");

                    b.HasKey("Id")
                        .HasName("pk_dang_ky_hoc_phan");

                    b.HasIndex("LopHocPhanId")
                        .HasDatabaseName("ix_dang_ky_hoc_phan_lop_hoc_phan_id");

                    b.HasIndex("NhomThucHanhId")
                        .HasDatabaseName("ix_dang_ky_hoc_phan_nhom_thuc_hanh_id");

                    b.HasIndex("SinhVienId")
                        .HasDatabaseName("ix_dang_ky_hoc_phan_sinh_vien_id");

                    b.ToTable("dang_ky_hoc_phan");
                });

            modelBuilder.Entity("UniversityRegistration.Models.GiangVien", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("id");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ho_ten");

                    b.Property<string>("KhoaId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("khoa_id");

                    b.Property<string>("MaGV")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ma_gv");

                    b.HasKey("Id")
                        .HasName("pk_giang_vien");

                    b.HasIndex("KhoaId")
                        .HasDatabaseName("ix_giang_vien_khoa_id");

                    b.ToTable("giang_vien");
                });

            modelBuilder.Entity("UniversityRegistration.Models.HocKy", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("id");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.Property<string>("TenHocKy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_hoc_ky");

                    b.HasKey("Id")
                        .HasName("pk_hoc_ky");

                    b.ToTable("hoc_ky");
                });

            modelBuilder.Entity("UniversityRegistration.Models.Khoa", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("id");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_khoa");

                    b.HasKey("Id")
                        .HasName("pk_khoa");

                    b.ToTable("khoa");
                });

            modelBuilder.Entity("UniversityRegistration.Models.KhoaDaoTao", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("id");

                    b.Property<string>("ChuongTrinhHocId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("chuong_trinh_hoc_id");

                    b.Property<string>("KhoaId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("khoa_id");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_bat_dau");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_ket_thuc");

                    b.Property<string>("TenKhoaDaoTao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_khoa_dao_tao");

                    b.HasKey("Id")
                        .HasName("pk_khoa_dao_tao");

                    b.HasIndex("ChuongTrinhHocId")
                        .HasDatabaseName("ix_khoa_dao_tao_chuong_trinh_hoc_id");

                    b.HasIndex("KhoaId")
                        .HasDatabaseName("ix_khoa_dao_tao_khoa_id");

                    b.ToTable("khoa_dao_tao");
                });

            modelBuilder.Entity("UniversityRegistration.Models.LichHocPhan", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("id");

                    b.Property<string>("LopHocPhanId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("lop_hoc_phan_id");

                    b.Property<string>("NhomThucHanhId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("nhom_thuc_hanh_id");

                    b.Property<string>("PhongHocId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("phong_hoc_id");

                    b.Property<int>("Thu")
                        .HasColumnType("int")
                        .HasColumnName("thu");

                    b.Property<int>("TietBatDau")
                        .HasColumnType("int")
                        .HasColumnName("tiet_bat_dau");

                    b.Property<int>("TietKetThuc")
                        .HasColumnType("int")
                        .HasColumnName("tiet_ket_thuc");

                    b.HasKey("Id")
                        .HasName("pk_lich_hoc_phan");

                    b.HasIndex("LopHocPhanId")
                        .HasDatabaseName("ix_lich_hoc_phan_lop_hoc_phan_id");

                    b.HasIndex("NhomThucHanhId")
                        .HasDatabaseName("ix_lich_hoc_phan_nhom_thuc_hanh_id");

                    b.HasIndex("PhongHocId")
                        .HasDatabaseName("ix_lich_hoc_phan_phong_hoc_id");

                    b.ToTable("lich_hoc_phan");
                });

            modelBuilder.Entity("UniversityRegistration.Models.LopDanhNghia", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("id");

                    b.Property<string>("KhoaDaoTaoId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("khoa_dao_tao_id");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_lop");

                    b.HasKey("Id")
                        .HasName("pk_lop_danh_nghia");

                    b.HasIndex("KhoaDaoTaoId")
                        .HasDatabaseName("ix_lop_danh_nghia_khoa_dao_tao_id");

                    b.ToTable("lop_danh_nghia");
                });

            modelBuilder.Entity("UniversityRegistration.Models.LopHocPhan", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("id");

                    b.Property<string>("GiangVienLTId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("giang_vien_lt_id");

                    b.Property<string>("HocKyId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("hoc_ky_id");

                    b.Property<string>("MonHocId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("mon_hoc_id");

                    b.Property<int>("SoLuongHienTaiLT")
                        .HasColumnType("int")
                        .HasColumnName("so_luong_hien_tai_lt");

                    b.Property<int>("SoLuongToiDaLT")
                        .HasColumnType("int")
                        .HasColumnName("so_luong_toi_da_lt");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("pk_lop_hoc_phan");

                    b.HasIndex("GiangVienLTId")
                        .HasDatabaseName("ix_lop_hoc_phan_giang_vien_lt_id");

                    b.HasIndex("HocKyId")
                        .HasDatabaseName("ix_lop_hoc_phan_hoc_ky_id");

                    b.HasIndex("MonHocId")
                        .HasDatabaseName("ix_lop_hoc_phan_mon_hoc_id");

                    b.ToTable("lop_hoc_phan");
                });

            modelBuilder.Entity("UniversityRegistration.Models.MonHoc", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("id");

                    b.Property<string>("ChuongTrinhHocId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("chuong_trinh_hoc_id");

                    b.Property<string>("KhoaId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("khoa_id");

                    b.Property<string>("TenMonHoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_mon_hoc");

                    b.Property<int>("TinChiLT")
                        .HasColumnType("int")
                        .HasColumnName("tin_chi_lt");

                    b.Property<int>("TinChiTH")
                        .HasColumnType("int")
                        .HasColumnName("tin_chi_th");

                    b.HasKey("Id")
                        .HasName("pk_mon_hoc");

                    b.HasIndex("ChuongTrinhHocId")
                        .HasDatabaseName("ix_mon_hoc_chuong_trinh_hoc_id");

                    b.HasIndex("KhoaId")
                        .HasDatabaseName("ix_mon_hoc_khoa_id");

                    b.ToTable("mon_hoc");
                });

            modelBuilder.Entity("UniversityRegistration.Models.MonHocGiangVien", b =>
                {
                    b.Property<string>("MonHocId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("mon_hoc_id");

                    b.Property<string>("GiangVienId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("giang_vien_id");

                    b.HasKey("MonHocId", "GiangVienId")
                        .HasName("pk_mon_hoc_giang_vien");

                    b.HasIndex("GiangVienId")
                        .HasDatabaseName("ix_mon_hoc_giang_vien_giang_vien_id");

                    b.ToTable("mon_hoc_giang_vien");
                });

            modelBuilder.Entity("UniversityRegistration.Models.NhomThucHanh", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("id");

                    b.Property<string>("GiangVienTHId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("giang_vien_th_id");

                    b.Property<string>("LopHocPhanId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("lop_hoc_phan_id");

                    b.Property<int>("SoLuongHienTai")
                        .HasColumnType("int")
                        .HasColumnName("so_luong_hien_tai");

                    b.Property<int>("SoLuongToiDa")
                        .HasColumnType("int")
                        .HasColumnName("so_luong_toi_da");

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_nhom");

                    b.HasKey("Id")
                        .HasName("pk_nhom_thuc_hanh");

                    b.HasIndex("GiangVienTHId")
                        .HasDatabaseName("ix_nhom_thuc_hanh_giang_vien_th_id");

                    b.HasIndex("LopHocPhanId")
                        .HasDatabaseName("ix_nhom_thuc_hanh_lop_hoc_phan_id");

                    b.ToTable("nhom_thuc_hanh");
                });

            modelBuilder.Entity("UniversityRegistration.Models.PhongHoc", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("id");

                    b.Property<string>("DiaDiem")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("dia_diem");

                    b.Property<string>("LoaiPhong")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("loai_phong");

                    b.Property<int>("SucChua")
                        .HasColumnType("int")
                        .HasColumnName("suc_chua");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_phong");

                    b.HasKey("Id")
                        .HasName("pk_phong_hoc");

                    b.ToTable("phong_hoc");
                });

            modelBuilder.Entity("UniversityRegistration.Models.SinhVien", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("id");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ho_ten");

                    b.Property<string>("LopDanhNghiaId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("lop_danh_nghia_id");

                    b.Property<string>("MaSV")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ma_sv");

                    b.HasKey("Id")
                        .HasName("pk_sinh_vien");

                    b.HasIndex("LopDanhNghiaId")
                        .HasDatabaseName("ix_sinh_vien_lop_danh_nghia_id");

                    b.ToTable("sinh_vien");
                });

            modelBuilder.Entity("UniversityRegistration.Models.DangKyHocPhan", b =>
                {
                    b.HasOne("UniversityRegistration.Models.LopHocPhan", "LopHocPhan")
                        .WithMany("DanhSachDangKyHocPhan")
                        .HasForeignKey("LopHocPhanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dang_ky_hoc_phan__danh_sach_lop_hoc_phan_lop_hoc_phan_id");

                    b.HasOne("UniversityRegistration.Models.NhomThucHanh", "NhomThucHanh")
                        .WithMany("DanhSachDangKyHocPhan")
                        .HasForeignKey("NhomThucHanhId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_dang_ky_hoc_phan__danh_sach_nhom_thuc_hanh_nhom_thuc_hanh_id");

                    b.HasOne("UniversityRegistration.Models.SinhVien", "SinhVien")
                        .WithMany("DanhSachDangKyHocPhan")
                        .HasForeignKey("SinhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dang_ky_hoc_phan__danh_sach_sinh_vien_sinh_vien_id");

                    b.Navigation("LopHocPhan");

                    b.Navigation("NhomThucHanh");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("UniversityRegistration.Models.GiangVien", b =>
                {
                    b.HasOne("UniversityRegistration.Models.Khoa", "Khoa")
                        .WithMany("DanhSachGiangVien")
                        .HasForeignKey("KhoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_giang_vien__danh_sach_khoa_khoa_id");

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("UniversityRegistration.Models.KhoaDaoTao", b =>
                {
                    b.HasOne("UniversityRegistration.Models.ChuongTrinhHoc", "ChuongTrinhHoc")
                        .WithMany()
                        .HasForeignKey("ChuongTrinhHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_khoa_dao_tao_chuong_trinh_hoc_chuong_trinh_hoc_id");

                    b.HasOne("UniversityRegistration.Models.Khoa", "Khoa")
                        .WithMany("DanhSachKhoaDaoTao")
                        .HasForeignKey("KhoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_khoa_dao_tao_khoa_khoa_id");

                    b.Navigation("ChuongTrinhHoc");

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("UniversityRegistration.Models.LichHocPhan", b =>
                {
                    b.HasOne("UniversityRegistration.Models.LopHocPhan", "LopHocPhan")
                        .WithMany("DanhSachLichHocPhan")
                        .HasForeignKey("LopHocPhanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_lich_hoc_phan__danh_sach_lop_hoc_phan_lop_hoc_phan_id");

                    b.HasOne("UniversityRegistration.Models.NhomThucHanh", "NhomThucHanh")
                        .WithMany("DanhSachLichHocPhan")
                        .HasForeignKey("NhomThucHanhId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_lich_hoc_phan__danh_sach_nhom_thuc_hanh_nhom_thuc_hanh_id");

                    b.HasOne("UniversityRegistration.Models.PhongHoc", "PhongHoc")
                        .WithMany("DanhSachLichHocPhan")
                        .HasForeignKey("PhongHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lich_hoc_phan__danh_sach_phong_hoc_phong_hoc_id");

                    b.Navigation("LopHocPhan");

                    b.Navigation("NhomThucHanh");

                    b.Navigation("PhongHoc");
                });

            modelBuilder.Entity("UniversityRegistration.Models.LopDanhNghia", b =>
                {
                    b.HasOne("UniversityRegistration.Models.KhoaDaoTao", "KhoaDaoTao")
                        .WithMany("DanhSachLopDanhNghia")
                        .HasForeignKey("KhoaDaoTaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lop_danh_nghia_khoa_dao_tao_khoa_dao_tao_id");

                    b.Navigation("KhoaDaoTao");
                });

            modelBuilder.Entity("UniversityRegistration.Models.LopHocPhan", b =>
                {
                    b.HasOne("UniversityRegistration.Models.GiangVien", "GiangVienLT")
                        .WithMany("DanhSachLopHocPhanLT")
                        .HasForeignKey("GiangVienLTId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lop_hoc_phan_giang_vien_giang_vien_lt_id");

                    b.HasOne("UniversityRegistration.Models.HocKy", "HocKy")
                        .WithMany("DanhSachLopHocPhan")
                        .HasForeignKey("HocKyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lop_hoc_phan_hoc_ky_hoc_ky_id");

                    b.HasOne("UniversityRegistration.Models.MonHoc", "MonHoc")
                        .WithMany("DanhSachLopHocPhan")
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lop_hoc_phan__danh_sach_mon_hoc_mon_hoc_id");

                    b.Navigation("GiangVienLT");

                    b.Navigation("HocKy");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("UniversityRegistration.Models.MonHoc", b =>
                {
                    b.HasOne("UniversityRegistration.Models.ChuongTrinhHoc", "ChuongTrinhHoc")
                        .WithMany("DanhSachMonHoc")
                        .HasForeignKey("ChuongTrinhHocId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_mon_hoc_chuong_trinh_hoc_chuong_trinh_hoc_id");

                    b.HasOne("UniversityRegistration.Models.Khoa", "Khoa")
                        .WithMany("DanhSachMonHoc")
                        .HasForeignKey("KhoaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_mon_hoc_khoa_khoa_id");

                    b.Navigation("ChuongTrinhHoc");

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("UniversityRegistration.Models.MonHocGiangVien", b =>
                {
                    b.HasOne("UniversityRegistration.Models.GiangVien", "GiangVien")
                        .WithMany("DanhSachMonHocGiangVien")
                        .HasForeignKey("GiangVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mon_hoc_giang_vien_giang_vien_giang_vien_id");

                    b.HasOne("UniversityRegistration.Models.MonHoc", "MonHoc")
                        .WithMany("DanhSachMonHocGiangVien")
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mon_hoc_giang_vien_mon_hoc_mon_hoc_id");

                    b.Navigation("GiangVien");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("UniversityRegistration.Models.NhomThucHanh", b =>
                {
                    b.HasOne("UniversityRegistration.Models.GiangVien", "GiangVienTH")
                        .WithMany("DanhSachNhomThucHanhTH")
                        .HasForeignKey("GiangVienTHId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_nhom_thuc_hanh_giang_vien_giang_vien_th_id");

                    b.HasOne("UniversityRegistration.Models.LopHocPhan", "LopHocPhan")
                        .WithMany("DanhSachNhomThucHanh")
                        .HasForeignKey("LopHocPhanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_nhom_thuc_hanh_lop_hoc_phan_lop_hoc_phan_id");

                    b.Navigation("GiangVienTH");

                    b.Navigation("LopHocPhan");
                });

            modelBuilder.Entity("UniversityRegistration.Models.SinhVien", b =>
                {
                    b.HasOne("UniversityRegistration.Models.LopDanhNghia", "LopDanhNghia")
                        .WithMany("DanhSachSinhVien")
                        .HasForeignKey("LopDanhNghiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sinh_vien_lop_danh_nghia_lop_danh_nghia_id");

                    b.Navigation("LopDanhNghia");
                });

            modelBuilder.Entity("UniversityRegistration.Models.ChuongTrinhHoc", b =>
                {
                    b.Navigation("DanhSachMonHoc");
                });

            modelBuilder.Entity("UniversityRegistration.Models.GiangVien", b =>
                {
                    b.Navigation("DanhSachLopHocPhanLT");

                    b.Navigation("DanhSachMonHocGiangVien");

                    b.Navigation("DanhSachNhomThucHanhTH");
                });

            modelBuilder.Entity("UniversityRegistration.Models.HocKy", b =>
                {
                    b.Navigation("DanhSachLopHocPhan");
                });

            modelBuilder.Entity("UniversityRegistration.Models.Khoa", b =>
                {
                    b.Navigation("DanhSachGiangVien");

                    b.Navigation("DanhSachKhoaDaoTao");

                    b.Navigation("DanhSachMonHoc");
                });

            modelBuilder.Entity("UniversityRegistration.Models.KhoaDaoTao", b =>
                {
                    b.Navigation("DanhSachLopDanhNghia");
                });

            modelBuilder.Entity("UniversityRegistration.Models.LopDanhNghia", b =>
                {
                    b.Navigation("DanhSachSinhVien");
                });

            modelBuilder.Entity("UniversityRegistration.Models.LopHocPhan", b =>
                {
                    b.Navigation("DanhSachDangKyHocPhan");

                    b.Navigation("DanhSachLichHocPhan");

                    b.Navigation("DanhSachNhomThucHanh");
                });

            modelBuilder.Entity("UniversityRegistration.Models.MonHoc", b =>
                {
                    b.Navigation("DanhSachLopHocPhan");

                    b.Navigation("DanhSachMonHocGiangVien");
                });

            modelBuilder.Entity("UniversityRegistration.Models.NhomThucHanh", b =>
                {
                    b.Navigation("DanhSachDangKyHocPhan");

                    b.Navigation("DanhSachLichHocPhan");
                });

            modelBuilder.Entity("UniversityRegistration.Models.PhongHoc", b =>
                {
                    b.Navigation("DanhSachLichHocPhan");
                });

            modelBuilder.Entity("UniversityRegistration.Models.SinhVien", b =>
                {
                    b.Navigation("DanhSachDangKyHocPhan");
                });
#pragma warning restore 612, 618
        }
    }
}
